=== Backbase/engagements-data/schema/v1/trigger-event.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Trigger Event",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "description": "The unique identifier of the trigger event."
    },
    "eventClassName": {
      "type": "string",
      "description": "A fully qualified class name for the trigger event."
    },
    "eventBusinessName": {
      "type": "string",
      "description": "A business name for the trigger event."
    },
    "recipientType": {
      "$ref": "#/$defs/RecipientType"
    },
    "extractor": {
      "type": "string",
      "description": "The SpEL expression to extract a recipient or subscription."
    },
    "subscriptionType": {
      "$ref": "#/$defs/SubscriptionType"
    },
    "eventSlicer": {
      "type": "string",
      "description": "The SpEL expression to process entries separately in case the event is an array."
    },
    "serviceAgreementExtractor": {
      "type": "string",
      "description": "The SpEL expression to extract a service agreement."
    },
    "generalNotifications": {
      "type": "array",
      "description": "One or more general notifications.",
      "items": {
        "$ref": "#/$defs/GeneralNotification"
      }
    }
  },
  "required": [
    "id"
  ],
  "additionalProperties": false,
  "$defs": {
    "RecipientType": {
      "type": "string",
      "description": "Identifies the type of recipient based on their subscription",
      "enum": [
        "subscription",
        "internal"
      ]
    },
    "SubscriptionType": {
      "type": "string",
      "description": "The entity type if recipientType is subscription.",
      "enum": [
        "arrangement"
      ]
    },
    "DeliveryOptions": {
      "type": "object",
      "title": "Delivery Option",
      "properties": {
        "channel": {
          "type": "string",
          "description": "A delivery channel."
        },
        "channelSettings": {
          "type": "string",
          "description": "A path to channel-specific settings that should be present in the import package."
        },
        "isEnabledByDefault": {
          "type": "boolean",
          "description": "Indicates whether the channel is enabled by default."
        },
        "isManageableByUser": {
          "type": "boolean",
          "description": "Indicates whether the user can manage preferences for the channel."
        },
        "routeInfo": {
          "type": "object",
          "description": "A key for mapping to the route of the web and mobile application."
        },
        "engagementTemplates": {
          "type": "array",
          "description": "One or more engagement templates.",
          "items": {
            "$ref": "#/$defs/EngagementTemplates"
          }
        }
      },
      "additionalProperties": false
    },
    "GeneralNotification": {
      "type": "object",
      "title": "General Notification",
      "properties": {
        "id": {
          "type": "string",
          "description": "The unique identifier of the general notification."
        },
        "name": {
          "type": "string",
          "description": "A business name for the general notification engagement."
        },
        "manageable": {
          "type": "boolean",
          "description": "Indicates whether a general notification is manageable via Engage App."
        },
        "userPreferenceEnabled": {
          "type": "boolean",
          "description": "Indicates whether a general notification has any user notification preferences."
        },
        "priority": {
          "type": "number",
          "minimum": 0,
          "maximum": 7,
          "description": "The delivery priority of the general notification. The range is from 0 to 7."
        },
        "additionalFilterLogic": {
          "type": "string",
          "description": "The SpEL expression to apply additional filtering based on the incoming event data. For example, to filter only credit transactions, the following expression is used: #triggeredEvent['creditDebitIndicator'] == 'CRDT'"
        },
        "userPreferenceDefaults": {
          "type": "string",
          "description": "Defines user preference default values for general notifications where the user can set their own value for their notification preferences."
        },
        "deliveryOptions": {
          "type": "array",
          "description": "One or more delivery options.",
          "items": {
            "$ref": "#/$defs/DeliveryOptions"
          }
        }
      },
      "additionalProperties": false
    },
    "EngagementTemplates": {
      "type": "object",
      "title": "Engagement Template",
      "properties": {
        "path": {
          "type": "string",
          "description": "A path to the engagement template file that should be present in the import package."
        },
        "content": {
          "type": "object",
          "description": "Engagement template content in JSON format."
        },
        "templateName": {
          "type": "string",
          "description": "A template name based on which the engagement template is created."
        },
        "locale": {
          "type": "string",
          "description": "A locale of the engagement template."
        }
      },
      "additionalProperties": false
    },
    "routeInfo": {
      "type": "object",
      "title": "Route Info",
      "properties": {
        "whereTo": {
          "type": "string",
          "description": "Route Name"
        },
        "data": {
          "type": "string",
          "description": "JSON String containing route data"
        }
      },
      "required": [
        "whereTo",
        "data"
      ],
      "additionalProperties": false
    }
  }
}

=== Backbase/engagements-data/collections/retail/general-notifications/event-general-notifications/transaction-added/event-general-notifications.json
{
  "$schema": "../../../../../schema/v1/trigger-event.json",
  "eventClassName": "com.backbase.transaction.persistence.event.spec.v1.TransactionsAddedEvent",
  "id": "transaction-added",
  "eventBusinessName": "Transaction Added",
  "recipientType": "subscription",
  "extractor": "#this['arrangementId']",
  "subscriptionType": "arrangement",
  "eventSlicer": "#this['transactions']",
  "generalNotifications": [
    {
      "id": "new-transaction-occurred",
      "name": "New Transaction Occurred",
      "userPreferenceEnabled": true,
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/new-transaction-occurred/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "transaction-view",
            "data": "{\"id\":\"{{event.id}}\",\"arrangementId\":\"{{event.arrangementId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/new-transaction-occurred/in-app-notification/en_US/engagement-template.json",
              "templateName": "new-transaction-occurred-in-app-notification",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "push",
          "channelSettings": "/new-transaction-occurred/push/push_channel-settings.json",
          "isEnabledByDefault": false,
          "routeInfo": {
            "whereTo": "transaction-view",
            "data": "{\"id\":\"{{event.id}}\",\"arrangementId\":\"{{event.arrangementId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/new-transaction-occurred/push/en_US/engagement-template.json",
              "templateName": "new-transaction-occurred-push",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/password-reset-success/event-general-notifications.json
{
  "eventClassName": "com.backbase.identity.accountrecovery.event.spec.v1.PasswordResetSuccessEvent",
  "id": "password-reset-success",
  "eventBusinessName": "Password Reset Success",
  "recipientType": "internal",
  "extractor": "#this['userInternalId']",
  "generalNotifications": [
    {
      "id": "password-reset-success",
      "name": "Password Reset Success",
      "userPreferenceEnabled": false,
      "manageable": false,
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/password-reset-success/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "content": {
                "subject": "You changed your password",
                "body": "file:/password-reset-success/email/assets/password-reset-success-template.html"
              },
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/retail/general-notifications/event-general-notifications/username-changed/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.user.manager.event.spec.v2.ChangeUsernameSecNotEvent",
  "id": "username-changed",
  "eventBusinessName": "Username Changed",
  "recipientType": "internal",
  "extractor": "#this['userInternalId']",
  "generalNotifications": [
    {
      "id": "username-changed",
      "name": "Username Changed",
      "userPreferenceEnabled": false,
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/username-changed/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "content": {
                "subject": "You changed your username",
                "body": "file:/username-changed/email/assets/username-changed-template.html"
              },
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/oneruntime/general-notifications/event-general-notifications/transaction-added/event-general-notifications.json
{
  "eventClassName": "com.backbase.transaction.persistence.event.spec.v1.TransactionsAddedEvent",
  "id": "transaction-added",
  "eventBusinessName": "Transaction Added",
  "recipientType": "subscription",
  "extractor": "#this['arrangementId']",
  "subscriptionType": "arrangement",
  "eventSlicer": "#this['transactions']",
  "generalNotifications": [
    {
      "id": "new-transaction-occurred",
      "name": "New Transaction Occurred Retail",
      "userPreferenceEnabled": true,
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/new-transaction-occurred-retail/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "transaction-view",
            "data": "{\"id\":\"{{event.id}}\",\"arrangementId\":\"{{event.arrangementId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/new-transaction-occurred-retail/in-app-notification/en_US/engagement-template.json",
              "templateName": "new-transaction-occurred-in-app-notification",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "push",
          "channelSettings": "/new-transaction-occurred-retail/push/push_channel-settings.json",
          "isEnabledByDefault": true,
          "routeInfo": {
            "whereTo": "transaction-view",
            "data": "{\"id\":\"{{event.id}}\",\"arrangementId\":\"{{event.arrangementId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/new-transaction-occurred-retail/push/en_US/engagement-template.json",
              "templateName": "new-transaction-occurred-push",
              "locale": "en_US"
            }
          ]
        }
      ]
    },
    {
      "id": "new-transaction-occurred-business",
      "name": "New Transaction Occurred Business",
      "userPreferenceEnabled": true,
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/new-transaction-occurred-business/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "transaction-view",
            "data": "{\"id\":\"{{event.id}}\",\"arrangementId\":\"{{event.arrangementId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/new-transaction-occurred-business/in-app-notification/en_US/engagement-template.json",
              "templateName": "new-transaction-occurred-in-app-notification",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "push",
          "channelSettings": "/new-transaction-occurred-business/push/push_channel-settings.json",
          "isEnabledByDefault": false,
          "routeInfo": {
            "whereTo": "transaction-view",
            "data": "{\"id\":\"{{event.id}}\",\"arrangementId\":\"{{event.arrangementId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/new-transaction-occurred-business/push/en_US/engagement-template.json",
              "templateName": "new-transaction-occurred-push",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/audit-export-completed/event-general-notifications.json
{
  "$schema": "../../../../../schema/v1/general-notification.json",
  "eventClassName": "com.backbase.audit.persistence.event.spec.v1.AuditExportCompletedEvent",
  "id": "audit-export-completed",
  "eventBusinessName": "Audit Export Completed",
  "recipientType": "internal",
  "extractor": "#this['userId']",
  "serviceAgreementExtractor": "#this['serviceAgreement']",
  "generalNotifications": [
    {
      "id": "audit-export-ready",
      "name": "Audit Export Ready",
      "userPreferenceEnabled": false,
      "manageable": false,
      "additionalFilterLogic": "#triggeredEvent['status'] == 'successful'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "audit-export-ready/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "audit-download-view",
            "data": "{\"link\":\"{{{event.link}}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/audit-export-ready/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    },
    {
      "id": "audit-export-failed",
      "name": "Audit Export Failed",
      "userPreferenceEnabled": false,
      "manageable": false,
      "additionalFilterLogic": "#triggeredEvent['status'] == 'failed'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "audit-export-failed/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "path": "/audit-export-failed/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/payment-order-updated/event-general-notifications.json
{
  "eventClassName": "com.backbase.payment.event.spec.v1.PaymentOrderUpdatedEvent",
  "id": "payment-order-updated",
  "eventBusinessName": "Payment Order Updated",
  "recipientType": "internal",
  "extractor": "#this['paymentOrder']['internalUserId']",
  "serviceAgreementExtractor": "#this['paymentOrder']['serviceAgreementId']",
  "generalNotifications": [
    {
      "id": "payment-status-updated-rejected",
      "name": "Payment Status Updated (Rejected)",
      "userPreferenceEnabled": true,
      "additionalFilterLogic": "#triggeredEvent['paymentOrder']['status'] == 'REJECTED'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/payment-status-updated-rejected/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "payment-view",
            "data": "{\"id\": \"{{event.paymentOrder.id}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/payment-status-updated-rejected/in-app-notification/en_US/engagement-template.json",
              "templateName": "payment-status-updated-rejected-in-app-notification",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "push",
          "channelSettings": "/payment-status-updated-rejected/push/push_channel-settings.json",
          "isEnabledByDefault": true,
          "routeInfo": {
            "whereTo": "payment-view",
            "data": "{\"id\": \"{{event.paymentOrder.id}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/payment-status-updated-rejected/push/en_US/engagement-template.json",
              "templateName": "payment-status-updated-rejected-push",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/conversation-history-export-completed/event-general-notifications.json
{
  "eventClassName": "com.backbase.employee.actions.event.spec.v1.ConvHistExportCompletedEvent",
  "id": "conv-hist-export-completed",
  "eventBusinessName": "Conversation History Export Completed",
  "recipientType": "internal",
  "extractor": "#this['userId']",
  "serviceAgreementExtractor": "#this['serviceAgreement']",
  "generalNotifications": [
    {
      "id": "conv-hist-export-ready",
      "name": "Conversation History Export Ready",
      "userPreferenceEnabled": false,
      "manageable": false,
      "additionalFilterLogic": "#triggeredEvent['status'] == 'successful'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "conv-hist-export-ready/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "conversation-trends-download-view",
            "data": "{\"exportId\":\"{{{event.exportId}}}\",\"fileType\":\"{{{event.fileType}}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/conv-hist-export-ready/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    },
    {
      "id": "conv-hist-export-failed",
      "name": "Conversation History Export Failed",
      "userPreferenceEnabled": false,
      "manageable": false,
      "additionalFilterLogic": "#triggeredEvent['status'] == 'failed'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "conv-hist-export-failed/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "path": "/conv-hist-export-failed/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/new-message-in-assigned-conversation/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.messages.pandp.event.spec.v4.NewMsgInAssignedConversationEvent",
  "id": "new-message-in-assigned-conversation",
  "eventBusinessName": "New Message In Assigned Conversation",
  "recipientType": "internal",
  "extractor": "#this['messageThreadAssignee']",
  "generalNotifications": [
    {
      "id": "new-message-in-assigned-conversation",
      "name": "New Message In Assigned Conversation",
      "userPreferenceEnabled": false,
      "manageable": false,
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "new-message-in-assigned-conversation/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "conversation-view",
            "data": "{\"id\":\"{{event.conversationId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/new-message-in-assigned-conversation/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}
