=== Backbase/engagements-data/schema/v1/trigger-event.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Trigger Event",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "description": "The unique identifier of the trigger event."
    },
    "eventClassName": {
      "type": "string",
      "description": "A fully qualified class name for the trigger event."
    },
    "eventBusinessName": {
      "type": "string",
      "description": "A business name for the trigger event."
    },
    "recipientType": {
      "$ref": "#/$defs/RecipientType"
    },
    "extractor": {
      "type": "string",
      "description": "The SpEL expression to extract a recipient or subscription."
    },
    "subscriptionType": {
      "$ref": "#/$defs/SubscriptionType"
    },
    "eventSlicer": {
      "type": "string",
      "description": "The SpEL expression to process entries separately in case the event is an array."
    },
    "serviceAgreementExtractor": {
      "type": "string",
      "description": "The SpEL expression to extract a service agreement."
    },
    "generalNotifications": {
      "type": "array",
      "description": "One or more general notifications.",
      "items": {
        "$ref": "#/$defs/GeneralNotification"
      }
    }
  },
  "required": [
    "id"
  ],
  "additionalProperties": false,
  "$defs": {
    "RecipientType": {
      "type": "string",
      "description": "Identifies the type of recipient based on their subscription",
      "enum": [
        "subscription",
        "internal"
      ]
    },
    "SubscriptionType": {
      "type": "string",
      "description": "The entity type if recipientType is subscription.",
      "enum": [
        "arrangement"
      ]
    },
    "DeliveryOptions": {
      "type": "object",
      "title": "Delivery Option",
      "properties": {
        "channel": {
          "type": "string",
          "description": "A delivery channel."
        },
        "channelSettings": {
          "type": "string",
          "description": "A path to channel-specific settings that should be present in the import package."
        },
        "isEnabledByDefault": {
          "type": "boolean",
          "description": "Indicates whether the channel is enabled by default."
        },
        "isManageableByUser": {
          "type": "boolean",
          "description": "Indicates whether the user can manage preferences for the channel."
        },
        "routeInfo": {
          "type": "object",
          "description": "A key for mapping to the route of the web and mobile application."
        },
        "engagementTemplates": {
          "type": "array",
          "description": "One or more engagement templates.",
          "items": {
            "$ref": "#/$defs/EngagementTemplates"
          }
        }
      },
      "additionalProperties": false
    },
    "GeneralNotification": {
      "type": "object",
      "title": "General Notification",
      "properties": {
        "id": {
          "type": "string",
          "description": "The unique identifier of the general notification."
        },
        "name": {
          "type": "string",
          "description": "A business name for the general notification engagement."
        },
        "manageable": {
          "type": "boolean",
          "description": "Indicates whether a general notification is manageable via Engage App."
        },
        "userPreferenceEnabled": {
          "type": "boolean",
          "description": "Indicates whether a general notification has any user notification preferences."
        },
        "priority": {
          "type": "number",
          "minimum": 0,
          "maximum": 7,
          "description": "The delivery priority of the general notification. The range is from 0 to 7."
        },
        "additionalFilterLogic": {
          "type": "string",
          "description": "The SpEL expression to apply additional filtering based on the incoming event data. For example, to filter only credit transactions, the following expression is used: #triggeredEvent['creditDebitIndicator'] == 'CRDT'"
        },
        "userPreferenceDefaults": {
          "type": "string",
          "description": "Defines user preference default values for general notifications where the user can set their own value for their notification preferences."
        },
        "deliveryOptions": {
          "type": "array",
          "description": "One or more delivery options.",
          "items": {
            "$ref": "#/$defs/DeliveryOptions"
          }
        }
      },
      "additionalProperties": false
    },
    "EngagementTemplates": {
      "type": "object",
      "title": "Engagement Template",
      "properties": {
        "path": {
          "type": "string",
          "description": "A path to the engagement template file that should be present in the import package."
        },
        "content": {
          "type": "object",
          "description": "Engagement template content in JSON format."
        },
        "templateName": {
          "type": "string",
          "description": "A template name based on which the engagement template is created."
        },
        "locale": {
          "type": "string",
          "description": "A locale of the engagement template."
        }
      },
      "additionalProperties": false
    },
    "routeInfo": {
      "type": "object",
      "title": "Route Info",
      "properties": {
        "whereTo": {
          "type": "string",
          "description": "Route Name"
        },
        "data": {
          "type": "string",
          "description": "JSON String containing route data"
        }
      },
      "required": [
        "whereTo",
        "data"
      ],
      "additionalProperties": false
    }
  }
}

=== Backbase/engagements-data/collections/retail/general-notifications/event-general-notifications/direct-deposit-success/event-general-notifications.json
{
  "eventClassName": "com.backbase.directdepositswitch.event.spec.v1.DirectDepositSuccessEvent",
  "id": "direct-deposit-success",
  "eventBusinessName": "Direct Deposit Success",
  "recipientType": "internal",
  "extractor": "#this['internalUserId']",
  "generalNotifications": [
    {
      "id": "direct-deposit-success",
      "name": "Direct Deposit Success",
      "userPreferenceEnabled": false,
      "manageable": false,
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/direct-deposit-success/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "path": "/direct-deposit-success/in-app-notification/en_US/engagement-template.json",
              "templateName": "direct-deposit-success-in-app-notification",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/phone-number-deleted/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.user.manager.event.spec.v2.DeletePhoneNumberSecNotEvent",
  "id": "phone-number-deleted",
  "eventBusinessName": "Phone Number Deleted",
  "recipientType": "internal",
  "extractor": "#this['userInternalId']",
  "generalNotifications": [
    {
      "id": "phone-number-deleted",
      "name": "Phone number deleted",
      "userPreferenceEnabled": false,
      "manageable": false,
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/phone-number-deleted/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "content": {
                "subject": "Phone number removed from online banking",
                "body": "file:/phone-number-deleted/email/assets/delete-phone-number-template.html"
              },
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/password-changed/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.user.manager.event.spec.v2.ChangeOwnPasswordSecNotEvent",
  "id": "password-changed",
  "eventBusinessName": "Password Changed",
  "recipientType": "internal",
  "extractor": "#this['userInternalId']",
  "generalNotifications": [
    {
      "id": "password-changed",
      "name": "Password Changed",
      "userPreferenceEnabled": false,
      "manageable": false,
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/password-changed/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "content": {
                "subject": "Password changed",
                "body": "file:/password-changed/email/assets/password-changed-template.html"
              },
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/postal-address-deleted/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.user.manager.event.spec.v2.DeletePostalAddressSecNotEvent",
  "id": "postal-address-deleted",
  "eventBusinessName": "Postal Address Deleted",
  "recipientType": "internal",
  "extractor": "#this['userInternalId']",
  "generalNotifications": [
    {
      "id": "postal-address-deleted",
      "name": "Postal Address Deleted",
      "userPreferenceEnabled": false,
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/postal-address-deleted/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "content": {
                "subject": "Mailing address removed from online banking",
                "body": "file:/postal-address-deleted/email/assets/postal-address-deleted-template.html"
              },
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/oneruntime/general-notifications/event-general-notifications/pp-ach-upcoming-cut-off-time/event-general-notifications.json
{
  "eventClassName": "com.backbase.positivepay.event.spec.v1.PpAchUpcomingCutOffTimeEvent",
  "id": "pp-ach-upcoming-cut-off-time",
  "eventBusinessName": "Positive Pay ACH Upcoming cut-off time",
  "recipientType": "subscription",
  "extractor": "#this['arrangementId']",
  "subscriptionType": "arrangement",
  "generalNotifications": [
    {
      "id": "pp-ach-upcoming-cut-off-time-business",
      "name": "Positive Pay ACH Upcoming Cut-Off Time - Business",
      "userPreferenceEnabled": true,
      "manageable": false,
      "additionalFilterLogic": "#lineOfBusiness != null ? #lineOfBusiness == 'BUSINESS' : true",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "pp-ach-upcoming-cut-off-time-business/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "routeInfo": {
            "whereTo": "positive-pay-ach-active-exceptions-view",
            "data": ""
          },
          "engagementTemplates": [
            {
              "path": "/pp-ach-upcoming-cut-off-time-business/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "email",
          "channelSettings": "pp-ach-upcoming-cut-off-time-business/email/email_channel-settings.json",
          "isEnabledByDefault": false,
          "engagementTemplates": [
            {
              "path": "/pp-ach-upcoming-cut-off-time-business/email/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/oneruntime/general-notifications/event-general-notifications/device-registered/event-general-notifications.json
{
  "eventClassName": "com.backbase.identity.device.event.spec.v1.DeviceAddedEvent",
  "id": "device-registered",
  "eventBusinessName": "Device Registered",
  "recipientType": "internal",
  "extractor": "#this['internalUserId']",
  "generalNotifications": [
    {
      "id": "device-registered",
      "name": "Device Registered",
      "userPreferenceEnabled": false,
      "manageable": false,
      "additionalFilterLogic": "#lineOfBusiness != null ? #lineOfBusiness == 'RETAIL' : true",
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/device-registered-retail/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "path": "/device-registered-retail/email/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    },
    {
      "id": "device-registered-business",
      "name": "Device Registered",
      "userPreferenceEnabled": false,
      "manageable": false,
      "additionalFilterLogic": "#lineOfBusiness != null ? #lineOfBusiness == 'BUSINESS' : false",
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/device-registered-business/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "path": "/device-registered-business/email/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/pp-ach-upcoming-cut-off-time/event-general-notifications.json
{
  "eventClassName": "com.backbase.positivepay.event.spec.v1.PpAchUpcomingCutOffTimeEvent",
  "id": "pp-ach-upcoming-cut-off-time",
  "eventBusinessName": "Positive Pay ACH Upcoming cut-off time",
  "recipientType": "subscription",
  "extractor": "#this['arrangementId']",
  "subscriptionType": "arrangement",
  "generalNotifications": [
    {
      "id": "pp-ach-upcoming-cut-off-time",
      "name": "Positive Pay ACH Upcoming cut-off time",
      "userPreferenceEnabled": true,
      "manageable": false,
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "pp-ach-upcoming-cut-off-time/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "routeInfo": {
            "whereTo": "positive-pay-ach-active-exceptions-view",
            "data": ""
          },
          "engagementTemplates": [
            {
              "path": "/pp-ach-upcoming-cut-off-time/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "email",
          "channelSettings": "pp-ach-upcoming-cut-off-time/email/email_channel-settings.json",
          "isEnabledByDefault": false,
          "engagementTemplates": [
            {
              "path": "/pp-ach-upcoming-cut-off-time/email/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/pending-approval/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.approval.persistence.event.spec.v3.PendingApprovalEvent",
  "id": "pending-approval",
  "eventBusinessName": "Pending Approval",
  "recipientType": "internal",
  "extractor": "#this['approverIds']",
  "serviceAgreementExtractor": "#this['approval']['serviceAgreementId']",
  "generalNotifications": [
    {
      "id": "payment-to-approve",
      "name": "Payment To Approve",
      "userPreferenceEnabled": true,
      "additionalFilterLogic": "#triggeredEvent['approval']['resource'] == 'Payments'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/payment-to-approve/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "payment-approve-view",
            "data": "{\"id\":\"{{event.approval.itemId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/payment-to-approve/in-app-notification/en_US/engagement-template.json",
              "templateName": "payment-to-approve-in-app-notification",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "push",
          "channelSettings": "/payment-to-approve/push/push_channel-settings.json",
          "isEnabledByDefault": true,
          "routeInfo": {
            "whereTo": "payment-approve-view",
            "data": "{\"id\":\"{{event.approval.itemId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/payment-to-approve/push/en_US/engagement-template.json",
              "templateName": "payment-to-approve-push",
              "locale": "en_US"
            }
          ]
        }
      ]
    },
    {
      "id": "contact-to-approve",
      "name": "Contact To Approve",
      "userPreferenceEnabled": true,
      "additionalFilterLogic": "#triggeredEvent['approval']['resource'] == 'Contacts'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/contact-to-approve/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "party-approve-view",
            "data": "{\"id\":\"{{event.approval.itemId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/contact-to-approve/in-app-notification/en_US/engagement-template.json",
              "templateName": "contact-to-approve-in-app-notification",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "push",
          "channelSettings": "/contact-to-approve/push/push_channel-settings.json",
          "isEnabledByDefault": true,
          "routeInfo": {
            "whereTo": "party-approve-view",
            "data": "{\"id\":\"{{event.approval.itemId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/contact-to-approve/push/en_US/engagement-template.json",
              "templateName": "contact-to-approve-push",
              "locale": "en_US"
            }
          ]
        }
      ]
    },
    {
      "id": "batch-to-approve",
      "name": "Batch To Approve",
      "userPreferenceEnabled": true,
      "additionalFilterLogic": "#triggeredEvent['approval']['resource'] == 'Batch'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/batch-to-approve/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "batch-approve-view",
            "data": "{\"id\":\"{{event.approval.itemId}}\", \"businessFunction\":\"{{event.approval.function}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/batch-to-approve/in-app-notification/en_US/engagement-template.json",
              "templateName": "batch-to-approve-in-app-notification",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}
