=== Backbase/engagements-data/schema/v1/trigger-event.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Trigger Event",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "description": "The unique identifier of the trigger event."
    },
    "eventClassName": {
      "type": "string",
      "description": "A fully qualified class name for the trigger event."
    },
    "eventBusinessName": {
      "type": "string",
      "description": "A business name for the trigger event."
    },
    "recipientType": {
      "$ref": "#/$defs/RecipientType"
    },
    "extractor": {
      "type": "string",
      "description": "The SpEL expression to extract a recipient or subscription."
    },
    "subscriptionType": {
      "$ref": "#/$defs/SubscriptionType"
    },
    "eventSlicer": {
      "type": "string",
      "description": "The SpEL expression to process entries separately in case the event is an array."
    },
    "serviceAgreementExtractor": {
      "type": "string",
      "description": "The SpEL expression to extract a service agreement."
    },
    "generalNotifications": {
      "type": "array",
      "description": "One or more general notifications.",
      "items": {
        "$ref": "#/$defs/GeneralNotification"
      }
    }
  },
  "required": [
    "id"
  ],
  "additionalProperties": false,
  "$defs": {
    "RecipientType": {
      "type": "string",
      "description": "Identifies the type of recipient based on their subscription",
      "enum": [
        "subscription",
        "internal"
      ]
    },
    "SubscriptionType": {
      "type": "string",
      "description": "The entity type if recipientType is subscription.",
      "enum": [
        "arrangement"
      ]
    },
    "DeliveryOptions": {
      "type": "object",
      "title": "Delivery Option",
      "properties": {
        "channel": {
          "type": "string",
          "description": "A delivery channel."
        },
        "channelSettings": {
          "type": "string",
          "description": "A path to channel-specific settings that should be present in the import package."
        },
        "isEnabledByDefault": {
          "type": "boolean",
          "description": "Indicates whether the channel is enabled by default."
        },
        "isManageableByUser": {
          "type": "boolean",
          "description": "Indicates whether the user can manage preferences for the channel."
        },
        "routeInfo": {
          "type": "object",
          "description": "A key for mapping to the route of the web and mobile application."
        },
        "engagementTemplates": {
          "type": "array",
          "description": "One or more engagement templates.",
          "items": {
            "$ref": "#/$defs/EngagementTemplates"
          }
        }
      },
      "additionalProperties": false
    },
    "GeneralNotification": {
      "type": "object",
      "title": "General Notification",
      "properties": {
        "id": {
          "type": "string",
          "description": "The unique identifier of the general notification."
        },
        "name": {
          "type": "string",
          "description": "A business name for the general notification engagement."
        },
        "manageable": {
          "type": "boolean",
          "description": "Indicates whether a general notification is manageable via Engage App."
        },
        "userPreferenceEnabled": {
          "type": "boolean",
          "description": "Indicates whether a general notification has any user notification preferences."
        },
        "priority": {
          "type": "number",
          "minimum": 0,
          "maximum": 7,
          "description": "The delivery priority of the general notification. The range is from 0 to 7."
        },
        "additionalFilterLogic": {
          "type": "string",
          "description": "The SpEL expression to apply additional filtering based on the incoming event data. For example, to filter only credit transactions, the following expression is used: #triggeredEvent['creditDebitIndicator'] == 'CRDT'"
        },
        "userPreferenceDefaults": {
          "type": "string",
          "description": "Defines user preference default values for general notifications where the user can set their own value for their notification preferences."
        },
        "deliveryOptions": {
          "type": "array",
          "description": "One or more delivery options.",
          "items": {
            "$ref": "#/$defs/DeliveryOptions"
          }
        }
      },
      "additionalProperties": false
    },
    "EngagementTemplates": {
      "type": "object",
      "title": "Engagement Template",
      "properties": {
        "path": {
          "type": "string",
          "description": "A path to the engagement template file that should be present in the import package."
        },
        "content": {
          "type": "object",
          "description": "Engagement template content in JSON format."
        },
        "templateName": {
          "type": "string",
          "description": "A template name based on which the engagement template is created."
        },
        "locale": {
          "type": "string",
          "description": "A locale of the engagement template."
        }
      },
      "additionalProperties": false
    },
    "routeInfo": {
      "type": "object",
      "title": "Route Info",
      "properties": {
        "whereTo": {
          "type": "string",
          "description": "Route Name"
        },
        "data": {
          "type": "string",
          "description": "JSON String containing route data"
        }
      },
      "required": [
        "whereTo",
        "data"
      ],
      "additionalProperties": false
    }
  }
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/pp-check-upcoming-cut-off-time/event-general-notifications.json
{
  "eventClassName": "com.backbase.positivepay.event.spec.v1.PpCheckUpcomingCutOffTimeEvent",
  "id": "pp-check-upcoming-cut-off-time",
  "eventBusinessName": "Positive Pay Check Upcoming cut-off time",
  "recipientType": "subscription",
  "extractor": "#this['arrangementId']",
  "subscriptionType": "arrangement",
  "generalNotifications": [
    {
      "id": "pp-check-upcoming-cut-off-time",
      "name": "Positive Pay Check Upcoming cut-off time",
      "userPreferenceEnabled": true,
      "manageable": false,
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "pp-check-upcoming-cut-off-time/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "routeInfo": {
            "whereTo": "positive-pay-check-active-exceptions-view",
            "data": ""
          },
          "engagementTemplates": [
            {
              "path": "/pp-check-upcoming-cut-off-time/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "email",
          "channelSettings": "pp-check-upcoming-cut-off-time/email/email_channel-settings.json",
          "isEnabledByDefault": false,
          "engagementTemplates": [
            {
              "path": "/pp-check-upcoming-cut-off-time/email/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/postal-address-added/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.user.manager.event.spec.v2.AddPostalAddressSecNotEvent",
  "id": "postal-address-added",
  "eventBusinessName": "Postal Address Added",
  "recipientType": "internal",
  "extractor": "#this['userInternalId']",
  "generalNotifications": [
    {
      "id": "postal-address-added",
      "name": "Postal Address Added",
      "userPreferenceEnabled": false,
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/postal-address-added/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "content": {
                "subject": "Mailing address added to online banking",
                "body": "file:/postal-address-added/email/assets/postal-address-added-template.html"
              },
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/pp-check-exceptions-created/event-general-notifications.json
{
    "eventClassName": "com.backbase.positivepay.event.spec.v1.PpCheckExceptionsCreatedEvent",
    "id": "pp-check-exceptions-created",
    "eventBusinessName": "Positive Pay Check Exceptions Created",
    "recipientType": "subscription",
    "extractor": "#this['arrangementId']",
    "subscriptionType": "arrangement",
    "generalNotifications": [
      {
        "id": "pp-check-exceptions-created",
        "name": "Positive Pay Check Exceptions Created",
        "userPreferenceEnabled": true,
        "manageable": false,
        "deliveryOptions": [
          {
            "channel": "in-app-notification",
            "channelSettings": "pp-check-exceptions-created/in-app-notification/in-app_channel-settings.json",
            "isEnabledByDefault": true,
            "routeInfo": {
              "whereTo": "positive-pay-check-active-exceptions-view",
              "data": ""
            },
            "engagementTemplates": [
              {
                "path": "/pp-check-exceptions-created/in-app-notification/en_US/engagement-template.json",
                "locale": "en_US"
              }
            ]
          }
        ]
      }
    ]
  }

=== Backbase/engagements-data/collections/oneruntime/general-notifications/event-general-notifications/pp-check-exceptions-created/event-general-notifications.json
{
  "eventClassName": "com.backbase.positivepay.event.spec.v1.PpCheckExceptionsCreatedEvent",
  "id": "pp-check-exceptions-created",
  "eventBusinessName": "Positive Pay Check Exceptions Created",
  "recipientType": "subscription",
  "extractor": "#this['arrangementId']",
  "subscriptionType": "arrangement",
  "generalNotifications": [
    {
      "id": "pp-check-exceptions-created-business",
      "name": "Positive Pay Check Exceptions Created - Business",
      "userPreferenceEnabled": true,
      "manageable": false,
      "additionalFilterLogic": "#lineOfBusiness != null ? #lineOfBusiness == 'BUSINESS' : true",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "pp-check-exceptions-created-business/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "positive-pay-check-active-exceptions-view",
            "data": ""
          },
          "engagementTemplates": [
            {
              "path": "/pp-check-exceptions-created-business/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        },
        {
          "channel": "email",
          "channelSettings": "pp-check-exceptions-created-business/email/email_channel-settings.json",
          "isEnabledByDefault": false,
          "engagementTemplates": [
            {
              "path": "/pp-check-exceptions-created-business/email/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/retail/general-notifications/event-general-notifications/postal-address-updated/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.user.manager.event.spec.v2.UpdatePostalAddressSecNotEvent",
  "id": "postal-address-updated",
  "eventBusinessName": "Postal Address Updated",
  "recipientType": "internal",
  "extractor": "#this['userInternalId']",
  "generalNotifications": [
    {
      "id": "postal-address-updated",
      "name": "Postal Address Updated",
      "userPreferenceEnabled": false,
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/postal-address-updated/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "content": {
                "subject": "Mailing address for online banking was changed",
                "body": "file:/postal-address-updated/email/assets/postal-address-updated-template.html"
              },
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/business/general-notifications/event-general-notifications/phone-number-updated/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.user.manager.event.spec.v2.UpdatePhoneNumberSecNotEvent",
  "id": "phone-number-updated",
  "eventBusinessName": "Phone Number Updated",
  "recipientType": "internal",
  "extractor": "#this['userInternalId']",
  "generalNotifications": [
    {
      "id": "phone-number-updated",
      "name": "Phone number updated",
      "userPreferenceEnabled": false,
      "manageable": false,
      "deliveryOptions": [
        {
          "channel": "email",
          "channelSettings": "/phone-number-updated/email/email_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "content": {
                "subject": "Phone number updated to online banking",
                "body": "file:/phone-number-updated/email/assets/phone-number-updated-template.html"
              },
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/retail/general-notifications/event-general-notifications/message-data-export-created/event-general-notifications.json
{
  "eventClassName": "com.backbase.dbs.messages.pandp.event.spec.v1.MessageDataExportCreatedEvent",
  "id": "message-data-export-completed",
  "eventBusinessName": "Message Data Export Completed",
  "recipientType": "internal",
  "extractor": "#this['userId']",
  "serviceAgreementExtractor": "#this['serviceAgreement']",
  "generalNotifications": [
    {
      "id": "message-data-export-ready",
      "name": "Message Data Export Ready",
      "userPreferenceEnabled": false,
      "manageable": false,
      "additionalFilterLogic": "#triggeredEvent['status'] == 'successful'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "message-data-export-ready/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "message-data-download-view",
            "data": "{\"exportId\":\"{{{event.exportId}}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/message-data-export-ready/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    },
    {
      "id": "message-data-export-failed",
      "name": "Message Data Export Failed",
      "userPreferenceEnabled": false,
      "manageable": false,
      "additionalFilterLogic": "#triggeredEvent['status'] == 'failed'",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "message-data-export-failed/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "engagementTemplates": [
            {
              "path": "/message-data-export-failed/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}

=== Backbase/engagements-data/collections/oneruntime/general-notifications/event-general-notifications/import-letter-of-credit-status-updated/event-general-notifications.json
{
  "eventClassName": "com.backbase.lending.tradefinance.letterofcredit.event.spec.v1.ImportLetterOfCreditStatusUpdatedEvent",
  "id": "import-letter-of-credit-status-updated",
  "eventBusinessName": "Import Letter of Credit Status Updated",
  "recipientType": "internal",
  "extractor": "#this['contributorsIds']",
  "serviceAgreementExtractor": "#this['serviceAgreementId']",
  "generalNotifications": [
    {
      "id": "import-letter-of-credit-status-updated",
      "name": "Import Letter of Credit Status Updated",
      "userPreferenceEnabled": true,
      "manageable": false,
      "additionalFilterLogic": "{'BANK_REVIEW', 'BANK_APPROVED', 'BANK_REJECTED', 'INTERNAL_REJECTED', 'ISSUED', 'DOCUMENT_REVIEW', 'DISCREPANCIES_FOUND', 'PENDING_SETTLEMENT', 'SETTLED', 'EXPIRED', 'CANCELLED'}.contains(#triggeredEvent['status'])",
      "deliveryOptions": [
        {
          "channel": "in-app-notification",
          "channelSettings": "/import-letter-of-credit-status-updated/in-app-notification/in-app_channel-settings.json",
          "isEnabledByDefault": true,
          "isManageableByUser": false,
          "routeInfo": {
            "whereTo": "import-lc-view",
            "data": "{\"id\":\"{{event.lcId}}\"}"
          },
          "engagementTemplates": [
            {
              "path": "/import-letter-of-credit-status-updated/in-app-notification/en_US/engagement-template.json",
              "locale": "en_US"
            }
          ]
        }
      ]
    }
  ]
}
